name: Docker Image CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create env file
              run: echo "${{ secrets.NEXUS_ENV_PRODUCTION }}" > .env.production
            - name: Build the Docker image
              run: docker build --progress=plain -t vietct/nexus-server:v1 .
            - name: Log in to Docker Hub
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Push the Docker image
              run: docker push vietct/nexus-server:v1

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.HOST_USERNAME }}
                  password: ${{ secrets.HOST_PASSWORD }}
                  script: |
                      docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
                      docker pull vietct/nexus-server:v1
                      docker stop nexus-server
                      docker rm nexus-server
                      docker run -dp 4000:4000 --name nexus-server --restart unless-stopped vietct/nexus-server:v1
                      docker image prune -f
